version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    labels: [ "deps", "security", "dependabot" ]
    commit-message:
      prefix: "chore"
      include: "scope"
    security-updates-only: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels: [ "deps", "security", "dependabot" ]
    security-updates-only: true
